Models/ProductQrCode.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Seed_Admin;

public partial class ProductQrCode : EntitiesBase
{
    public override long Id { get; set; }

    public long RequestId { get; set; }
    public long BatchId { get; set; }

    public long ProductId { get; set; }
    public long PackageType_ID { get; set; }
    public long SKUSize_ID { get; set; }

    public string? QrCode_Base64 { get; set; }

    public string QrCode { get; set; } = null!;

    public long DecimalValue { get; set; }
    public string YYYYMM { get; set; }
    public decimal? Points { get; set; }

    public bool IsScanned { get; set; }

    [NotMapped]public long SrNo { get; set; }
    [NotMapped]public string Status { get; set; }
    [NotMapped]public string Reason { get; set; }
    [NotMapped]public long CreatedDate_Ticks { get; set; }
    [NotMapped] public long LastModifiedDate_Ticks { get; set; }
    [NotMapped] public string Product_Text { get; set; }
    [NotMapped] public string PackageType_Text { get; set; }
    [NotMapped] public string SKUSize_Text { get; set; }
}

Controllers/ProductQRCodeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Newtonsoft.Json.Linq;
using Seed_Admin.Controllers;
using Seed_Admin.Infra;
using Seed_Admin.Models;
using System.Collections.Generic;
using System.Data;

namespace Seed_Admin.Areas.Admin.Controllers
{

	public class ProductQRCodeController : BaseController<ResponseModel<ProductQrCode>>
	{
		public ProductQRCodeController(IRepositoryWrapper repository) : base(repository) { }

		// GET: Admin/LoyaltyPoint
		public ActionResult Index()
		{
			return View(CommonViewModel);
		}

		[HttpGet]
		public IActionResult GetData(JqueryDatatableParam param)
		{
			var result = new PagedResult();

			if (Common.IsAdmin())
				try
				{
					long batchId = Convert.ToInt64((string)HttpContext.Request.Query["BatchId"] ?? "0");

					var listQrcode = _context.Using<ProductQrCode>().GetByCondition(x => batchId > 0 ? x.BatchId == batchId : true).ToList();

					var dictProduct = _context.Using<Product>().GetAll().ToDictionary(x => x.Id);
					var dictPackageType = _context.Using<PackageType>().GetAll().ToDictionary(x => x.Id);
					var dictSKUSize = _context.Using<SKUSize>().GetAll().ToDictionary(x => x.Id);

					var listQrcode_Filtered = new List<ProductQrCode>();

					if (batchId > 0)
						listQrcode_Filtered = listQrcode.Select(g => new ProductQrCode()
										{
											BatchId = g.BatchId,
											RequestId = g.RequestId,
											Points = g.Points,
											QrCode = g.QrCode ?? "",
											ProductId = g.ProductId,
											PackageType_ID = g.PackageType_ID,
											SKUSize_ID = g.SKUSize_ID,
											CreatedDate = g.CreatedDate
										}).ToList();

					else
						listQrcode_Filtered = listQrcode.GroupBy(x => new { x.BatchId, x.RequestId, x.ProductId, x.PackageType_ID, x.SKUSize_ID, x.CreatedDate })
									.Select(g => new ProductQrCode()
									{
										BatchId = g.Key.BatchId,
										RequestId = g.Key.RequestId,
										Points = g.Count(),
										//Items = g.ToList()
										QrCode = (g.ToList().OrderBy(x => x.DecimalValue).FirstOrDefault()?.QrCode ?? "") + " - " + (g.ToList().OrderBy(x => x.DecimalValue).LastOrDefault()?.QrCode ?? ""),
										ProductId = g.Key.ProductId,
										PackageType_ID = g.Key.PackageType_ID,
										SKUSize_ID = g.Key.SKUSize_ID,
										CreatedDate = g.Key.CreatedDate
									}).ToList();

					var list = listQrcode_Filtered.Select(x =>
					{
						dictProduct.TryGetValue(x.ProductId, out var lp);
						dictPackageType.TryGetValue(x.PackageType_ID, out var lpt);
						dictSKUSize.TryGetValue(x.SKUSize_ID, out var ls);
						return new ProductQrCode
						{
							Id = x.Id,
							BatchId = x.BatchId,
							RequestId = x.RequestId,
							//QrCode_Base64 = x.QrCode_Base64,
							QrCode = x.QrCode,
							Points = x.Points,
							IsScanned = x.IsScanned,

							ProductId = lp?.Id ?? 0,
							Product_Text = lp?.Name ?? "",
							PackageType_ID = lpt?.Id ?? 0,
							PackageType_Text = lpt?.PackageTypeName ?? "",
							SKUSize_ID = ls?.Id ?? 0,
							SKUSize_Text = ls?.SKUSizeName ?? "",
							CreatedDate_Text = x.CreatedDate?.ToString("dd/MM/yyyy HH:mm:ss").Replace("-", "/") ?? "",
							//LastModifiedDate_Text = x.LastModifiedDate?.ToString("dd/MM/yyyy HH:mm:ss").Replace("-", "/") ?? "",
							CreatedDate_Ticks = x.CreatedDate?.Ticks ?? 0,
							//LastModifiedDate_Ticks = x.LastModifiedDate?.Ticks ?? 0
						};
					}).ToList();

					var recordsTotal = list.Count();
					IEnumerable<ProductQrCode> query = list;

					// Filter (Search)
					if (!string.IsNullOrWhiteSpace(param.sSearch))
					{
						query = query.Where(x =>
							(x.QrCode?.Contains(param.sSearch, StringComparison.OrdinalIgnoreCase) ?? false) ||
							(x.Product_Text?.Contains(param.sSearch, StringComparison.OrdinalIgnoreCase) ?? false) ||
							(x.PackageType_Text?.Contains(param.sSearch, StringComparison.OrdinalIgnoreCase) ?? false) ||
							(x.SKUSize_Text?.Contains(param.sSearch, StringComparison.OrdinalIgnoreCase) ?? false) ||
							x.Points.ToString().Contains(param.sSearch) ||
							x.CreatedDate_Text.Contains(param.sSearch)
						);
					}

					// Sort
					string sortColumn = HttpContext.Request.Query.ContainsKey("iSortCol_0") && HttpContext.Request.Query.ContainsKey($"mDataProp_{HttpContext.Request.Query["iSortCol_0"]}") ? Convert.ToString(HttpContext.Request.Query[$"mDataProp_{HttpContext.Request.Query["iSortCol_0"]}"]) : "";

					query = sortColumn?.ToLower() switch
					{
						"requestid" => Convert.ToString(HttpContext.Request.Query["sSortDir_0"]).ToLower() == "asc" ? query.OrderBy(x => x.RequestId) : query.OrderByDescending(x => x.RequestId),
						"qrcode" => Convert.ToString(HttpContext.Request.Query["sSortDir_0"]).ToLower() == "asc" ? query.OrderBy(x => x.QrCode) : query.OrderByDescending(x => x.QrCode),
						"points" => Convert.ToString(HttpContext.Request.Query["sSortDir_0"]).ToLower() == "asc" ? query.OrderBy(x => x.Points) : query.OrderByDescending(x => x.Points),
						"generatedate_text" => Convert.ToString(HttpContext.Request.Query["sSortDir_0"]).ToLower() == "asc" ? query.OrderBy(x => x.CreatedDate?.Ticks) : query.OrderByDescending(x => x.CreatedDate?.Ticks),
						"lastmodifieddate_text" => Convert.ToString(HttpContext.Request.Query["sSortDir_0"]).ToLower() == "asc" ? query.OrderBy(x => x.LastModifiedDate?.Ticks) : query.OrderByDescending(x => x.LastModifiedDate?.Ticks),

						_ => query.OrderByDescending(x => batchId > 0 ? x.LastModifiedDate?.Ticks : x.RequestId)
					};

					// Pagination
					var pagedData = param.iDisplayLength > -1 ? query.Skip(param.iDisplayStart).Take(param.iDisplayLength).ToList() : query.ToList();

					return Json(new { param.sEcho, iTotalRecords = pagedData.Count(), iTotalDisplayRecords = recordsTotal, aaData = pagedData }, new System.Text.Json.JsonSerializerOptions());
				}
				catch (Exception ex) { }

			return Json(new { param.sEcho, iTotalRecords = 0, iTotalDisplayRecords = 0, aaData = new JArray() }, new System.Text.Json.JsonSerializerOptions());
		}

		//[CustomAuthorizeAttribute(AccessType_Enum.Read)]
		public ActionResult Partial_AddEditForm()
		{
			if (!Common.IsAdmin())
			{
				CommonViewModel.IsSuccess = false;
				CommonViewModel.StatusCode = ResponseStatusCode.Error;
				CommonViewModel.Message = ResponseStatusMessage.UnAuthorize;

				return Json(CommonViewModel);
			}



			var dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_Product_Combo", null, true);

			if (dt != null && dt.Rows.Count > 0)
				foreach (DataRow dr in dt.Rows)
					CommonViewModel.SelectListItems.Add(new SelectListItem_Custom(dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "0", dr["Name"] != DBNull.Value ? Convert.ToString(dr["Name"]) : "", "Product"));

			return PartialView("_Partial_AddEditForm", CommonViewModel);
		}

		[HttpPost]
		//[CustomAuthorizeAttribute(AccessType_Enum.Write)]
		public ActionResult Save(long ProductId, long PackageType_ID, long SKUSize_ID, int NoOfQRCode, int MinPointRange, int MaxPointRange)
		{
			try
			{
				#region Validation

				if (!Common.IsAdmin())
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;
					CommonViewModel.Message = ResponseStatusMessage.UnAuthorize;

					return Json(CommonViewModel);
				}
				if (ProductId <= 0)
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;
					CommonViewModel.Message = "Please select Product.";

					return Json(CommonViewModel);
				}
				if (PackageType_ID <= 0)
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;
					CommonViewModel.Message = "Please select Package type.";

					return Json(CommonViewModel);
				}
				if (SKUSize_ID <= 0)
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;
					CommonViewModel.Message = "Please select SKU Size.";

					return Json(CommonViewModel);
				}


				if (NoOfQRCode <= 0)
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;
					CommonViewModel.Message = "Please enter No. Of QR Code.";

					return Json(CommonViewModel);
				}

				#endregion

				var (IsSuccess, response, Id) = (false, ResponseStatusMessage.Error, 0M);

				List<SqlParameter> oParams = new List<SqlParameter>();

				oParams.Add(new SqlParameter("@ProductId", SqlDbType.BigInt) { Value = ProductId });
				oParams.Add(new SqlParameter("@PackageType_ID", SqlDbType.BigInt) { Value = PackageType_ID });
				oParams.Add(new SqlParameter("@SKUSize_ID", SqlDbType.BigInt) { Value = SKUSize_ID });
				oParams.Add(new SqlParameter("@NoOfQRCode", SqlDbType.Int) { Value = NoOfQRCode });
				oParams.Add(new SqlParameter("@MinValue", SqlDbType.Int) { Value = MinPointRange });
				oParams.Add(new SqlParameter("@MaxValue", SqlDbType.Int) { Value = MaxPointRange });

				oParams.Add(new SqlParameter("@Operated_By", SqlDbType.BigInt) { Value = AppHttpContextAccessor.GetSession(SessionKey.KEY_USER_ID) });

				(IsSuccess, response, Id) = DataContext_Command.ExecuteStoredProcedure("SP_Product_QR_Code_Generate", oParams, true);

				CommonViewModel.IsConfirm = true;
				CommonViewModel.IsSuccess = IsSuccess;
				CommonViewModel.StatusCode = IsSuccess ? ResponseStatusCode.Success : ResponseStatusCode.Error;
				CommonViewModel.Message = response;

				return Json(CommonViewModel);

			}
			catch (Exception ex) { }

			CommonViewModel.Message = ResponseStatusMessage.Error;
			CommonViewModel.IsSuccess = false;
			CommonViewModel.StatusCode = ResponseStatusCode.Error;

			return Json(CommonViewModel);
		}

		[HttpPost]
		//[CustomAuthorizeAttribute(AccessType_Enum.Delete)]
		public ActionResult DeleteConfirmed(long Id)
		{
			try
			{
				if (!Common.IsAdmin())
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;

Views/ProductQRCode/Index.cshtml
@model ResponseModel<ProductQrCode>
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";

	decimal RupeePerPoint = Convert.ToDecimal(AppHttpContextAccessor.AppConfiguration.GetSection("RupeePerPoint")?.Value ?? "0");
}

<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Product QR Code</h1>
			</div>
			<div class="col-sm-6">
				<div class="float-sm-right">
					@if (Common.IsAdmin() && Model.IsCreate == true)
					{
						<button type="button" id="btnAddNewItem" class="btn btn-primary btn-md pull-right mr-2 divformSave_Hide"
								onclick="fnLoadParialView('divformSave', '@Url.Action("Partial_AddEditForm", "ProductQRCode")')">
							<i class="fas fa-plus"></i> &nbsp; Generate Product QR Code(s)
						</button>
						<button type="button" id="btnBackToList" class="btn btn-warning btn-md pull-right mr-2 divformSave_Display d-none" onclick="fnCloseParialView('divformSave');">
							<i class="fas fa-arrow-left"></i> &nbsp; Back To List
						</button>
					}
				</div>
			</div>
		</div>
	</div>
</div>

<section class="content">
	<div class="container-fluid">

		<div class="row no-gooters">
			<section class="col-md-12">
				<div class="card">
					<div class="card-header divformSave_Display d-none">

						<div class="row no-gooters">
							<div class="col-md-12 p-0 m-0" id="divformSave"></div>
							<div class="clearfix"></div>
						</div>

					</div>

					<div class="card-body divformSave_Hide">
						<div class="row no-gooters">
							<div class="col-md-12 my-1">
								<table class="table table-bordered table-striped table-hover w-100" id="dataTable_ProductQRCode"></table>
							</div>
							<input type="hidden" id="searchTerm" value="@(Model.Data5 != null ? Model.Data5 : "")" />
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>
</section>

@section Scripts {

	@if (Common.IsAdmin())
	{
		<script type="text/javascript">

			var dataTableMain = null;

			$(document).ready(function () {
				setTimeout(function () {
					fnLoadTableData();
				}, 1000);
			});

			function fnLoadTableData() {
				if ($.fn.DataTable.isDataTable('#dataTable_ProductQRCode')) {
					$('#dataTable_ProductQRCode').DataTable().destroy();
				}

				dataTableMain = $("#dataTable_ProductQRCode").DataTable({
					"destroy": true,
					"pageLength": 50,
					"lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
					"sAjaxSource": "@Url.Action("GetData", "ProductQRCode")",
					//"sServerMethod": "POST",
					"bServerSide": true,
					"bProcessing": true,
					"bSearchable": true,
					"order": [[2, 'desc']],
					"language": { "emptyTable": "No record found.", "processing": '<i class="fa fa-spinner fa-spin fa-3x fa-fw" style="color:#2a2b2b;"></i><span class="sr-only">Loading...</span> ' },
					"fnServerParams": function (aoData) {
						//aoData.push({ "name": "PoNo", "value": "" + $('#PoNo').val() });
						aoData.push({ "name": "sSearch", "value": $('#searchTerm').val() });
					},
					"columns": [
						{ "title": "#", "data": null, "autoWidth": false, "searchable": true, "width": "5%", "class": "text-center" },
						{ "title": "Request No", "data": "RequestId", "autoWidth": true, "searchable": true },
						{ "title": "Product", "data": "Product_Text", "autoWidth": true, "searchable": true },
						{ "title": "PackageType", "data": "PackageType_Text", "autoWidth": true, "searchable": true },
						{ "title": "SKU Size", "data": "SKUSize_Text", "autoWidth": true, "searchable": true },
						{ "title": "QR Code", "data": "QrCode", "autoWidth": true, "searchable": true },
						{ "title": "QR Code Count", "data": "Points", "autoWidth": true, "searchable": true },
						{ "title": "Created Date", "data": "CreatedDate_Text", "autoWidth": true, "searchable": true }
						@* ,{
							"title": "Action", "data": null, "autoWidth": false, "searchable": false, "width": "5%",
							"render": function (data, type, row, meta) {
								if (data.IsClaimed == false)
									return '<div class="btn-group"><a class="btn btn-danger btn-sm btn-flat ml-2" href="javascript:void(0);" onclick="divShow(\'/DeleteConfirmed?Id=' + data.Id + '\');"><span class="nme"><i class="far fa-trash-alt"></i></span></a></div>';
								else return '';
							}
						} *@
					],
					"fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
						var index = iDisplayIndexFull + 1;
						$("td:first", nRow).html(index);
						return nRow;
					},
					initComplete: function (settings, json) { $('#searchTerm').val('').trigger('change'); }
				});

			}
			function fnChangeProductDetail($this, $type, $selector) {
			if (typeof $selector != 'undefined' && $selector != null && $selector.length > 0) {
				ShowLoader(true);

				 if (typeof $type != 'undefined' && $type != null && $type.length > 0 && $type == 'PACKTYPE') {
					$('#SKUSize_ID').empty().append('<option value="0">-- Select --</option>');
				 }
				




				var stateDropdown = $($selector);
				stateDropdown.empty();
				stateDropdown.append('<option value="0">-- Select --</option>');

				var $url = '@Url.Action("GetProductDetails", "ProductQRCode")?Type=' + $type + '&ParentId=' + $($this).val();

				if ($type === "PACKTYPE") {
					$url += "&Product=" + encodeURIComponent($($this).find("option:selected").text());
				}
				$.ajax({
					url: $url,
					type: 'GET',
					data: {},
					dataType: "json",
					success: function (response) {
						debugger;
						ShowLoader(false);
						$.each(response, function (index, state) {
							stateDropdown.append('<option value="' + state.Value + '">' + state.Text + '</option>');
						});

					},
					failure: function () { ShowLoader(false); CommonAlert_Error(null); },
					error: function () { ShowLoader(false); CommonAlert_Error(null); }
				});
			}
			}
			
			function fnSubmitForm_Success(response, $id) {
				debugger;
				if (response.StatusCode === 1) fnCloseParialView('divformSave', null);
				dataTableMain.ajax.reload();
			}

			function fnParialView_Loaded_Success($id, $isAlert) {
				$('html, body').scrollTop($('#' + $id).offset().top);
			}

			// function fnParialView_Close_Success($id) {
			// 	debugger;
			// 	dataTableMain.ajax.reload();
			// }
		</script>
	}
}

Views/ProductQRCode/_Partial_AddEditForm.cshtml
@model ResponseModel<ProductQrCode>

@{
	Layout = null;
}

<form id="formSave" action="@Url.Action("Save","ProductQRCode")" method="post" class="w-100">
	<div class="card card-info">

		<div class="card-header">
			<h3 class="card-title">Generate Product QR Code(s)</h3>
		</div>

		<div class="card-body">
			<div class="row no-gutters">
				<div class="col-12">
					<div class="form-group row">
						<label for="ProductId" class="col-sm-2 col-form-label text-right">Select Product</label>
						<div class="col-sm-4">
							<select id="ProductId" name="ProductId" class="form-control form-control-sm select2 w-100" onchange="fnChangeProductDetail(this, 'PACKTYPE', '#PackageType_ID')">
								<option value="0">-- Select --</option>
								@if (Model.SelectListItems != null)
								{
									foreach (var item in Model.SelectListItems)
									{
										<option value="@item.Value">@item.Text</option>
									}
								}
							</select>
						</div>
						<label class="col-sm-2 col-form-label text-right">Package Type</label>
						<div class="col-sm-4">
							<select class="form-control form-control-sm select2 w-100" id="PackageType_ID" name="PackageType_ID" onchange="fnChangeProductDetail(this, 'SKUSIZE', '#SKUSize_ID')">
								<option value="0">-- Select --</option>								
							</select>
						</div>
					</div>
					
					<div class="form-group row">						
						<label class="col-sm-2 col-form-label text-right">SKU Size</label>
						<div class="col-sm-4">
							<select class="form-control form-control-sm select2 w-100" id="SKUSize_ID" name="SKUSize_ID">
								<option value="0">-- Select --</option>
							</select>
						</div>
						
					</div>
					<div class="form-group row" style="padding-top: 33px !important;">
						<label for="NoOfQRCode" class="col-sm-2 col-form-label text-right">No. of QR Code</label>
						<div class="col-sm-4">
							<input type="text" class="form-control form-control-sm isNumberKey" id="NoOfQRCode" name="NoOfQRCode" autocomplete="off" />
						</div>
					</div>

					<div class="form-group row">
						<label for="MinPointRange" class="col-sm-2 col-form-label text-right">Point Range</label>
						<div class="col-sm-2">
							<div class="input-group">
								<div class="input-group-prepend">
									<span class="input-group-text input-group-text-sm">Min</span>
								</div>
								<input type="text" class="form-control form-control-sm isNumberKey" id="MinPointRange" name="MinPointRange" autocomplete="off" />
							</div>
						</div>
						<div class="col-sm-2">
							<div class="input-group">
								<div class="input-group-prepend">
									<span class="input-group-text input-group-text-sm">Max</span>
								</div>
								<input type="text" class="form-control form-control-sm isNumberKey" id="MaxPointRange" name="MaxPointRange" autocomplete="off" />
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="card-footer">
			<div class="row no-gutters">
				<div class="col-sm-1">&nbsp;</div>
				<div class="col-sm-6 text-left">
					<button type="button" class="btn btn-success btnSubmit">Save</button>
					<button type="button" class="btn btn-danger" onclick="fnCloseParialView('divformSave', '#dataTable_ProductQRCode');">Cancel</button>
				</div>
			</div>
		</div>
	</div>

</form>