Models/ProductBatch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Seed_Admin;

public partial class ProductBatch : EntitiesBase
{
    public override long Id { get; set; }
    public string ? BatchNo { get; set; } = null!;

    public long  ProductId { get; set; }
    public long PackageType_ID { get; set; }
    public long  SKUSize_ID { get; set; }


    public string? SeedType { get; set; }

    public decimal? Qty { get; set; }

    public long? MfgBy { get; set; }

    public DateTime? MfgDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string? Remark { get; set; }

    [NotMapped] public string MfgDate_Text { get; set; }
    [NotMapped] public string ExpiryDate_Text { get; set; }
    [NotMapped] public string MfgBy_Text { get; set; }
    [NotMapped] public string Product_Text { get; set; }
    [NotMapped] public string PackageType_Text { get; set; }
    [NotMapped] public string SKUSize_Text { get; set; }

}

Controllers/ProductBatchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Seed_Admin.Controllers;
using Seed_Admin.Infra;
using Seed_Admin.Models;
using System.Data;
using System.Globalization;

namespace Seed_Admin.Areas.Admin.Controllers
{

    public class ProductBatchController : BaseController<ResponseModel<ProductBatch>>
    {
        public ProductBatchController(IRepositoryWrapper repository) : base(repository) { }

        // GET: Admin/ProductBatch
        public ActionResult Index()
        {
            if (Common.IsSuperAdmin() || Common.IsAdmin()) CommonViewModel.ObjList = _context.Using<ProductBatch>().GetAll().ToList();

            var dictProduct = _context.Using<Product>().GetAll().ToDictionary(x => x.Id);
            var dictPackageType = _context.Using<PackageType>().GetAll().ToDictionary(x => x.Id);
            var dictSKUSize = _context.Using<SKUSize>().GetAll().ToDictionary(x => x.Id);

            for (int i = 0; i < CommonViewModel.ObjList.Count(); i++)
            {
                dictProduct.TryGetValue(CommonViewModel.ObjList[i].ProductId, out var lp);
                dictPackageType.TryGetValue(CommonViewModel.ObjList[i].PackageType_ID, out var lpt);
                dictSKUSize.TryGetValue(CommonViewModel.ObjList[i].SKUSize_ID, out var ls);
                CommonViewModel.ObjList[i].Product_Text = lp?.Name ?? "";
                CommonViewModel.ObjList[i].PackageType_Text = lpt?.PackageTypeName ?? "";
                CommonViewModel.ObjList[i].SKUSize_Text = ls?.SKUSizeName ?? "";
                CommonViewModel.ObjList[i].MfgDate_Text = CommonViewModel.ObjList[i].MfgDate?.ToString(Common.DateTimeFormat_ddMMyyyy);
                CommonViewModel.ObjList[i].ExpiryDate_Text = CommonViewModel.ObjList[i].ExpiryDate?.ToString(Common.DateTimeFormat_ddMMyyyy);
                CommonViewModel.ObjList[i].CreatedDate_Text = CommonViewModel.ObjList[i].CreatedDate?.ToString(Common.DateTimeFormat_ddMMyyyy_HHmm);
            }

            return View(CommonViewModel);
        }

        //[CustomAuthorizeAttribute(AccessType_Enum.Read)]
        public ActionResult Partial_AddEditForm(long Id = 0, bool IsProductQRView = false)
        {
            if (!(Common.IsSuperAdmin() || Common.IsAdmin()))
            {
                CommonViewModel.IsSuccess = false;
                CommonViewModel.StatusCode = ResponseStatusCode.Error;
                CommonViewModel.Message = ResponseStatusMessage.UnAuthorize;

                return Json(CommonViewModel);
            }

            long currentCount = _context.Using<ProductBatch>().GetByCondition(x => x.CreatedDate.Value.Year == DateTime.Now.Year).Count();

            CommonViewModel.Obj = new ProductBatch()
            {
                BatchNo = DateTime.Now.ToString("yyyyMMdd") + (currentCount + 1).ToString().PadLeft(10, '0'),
                MfgDate = DateTime.Now.Date,
                ExpiryDate = DateTime.Now.Date.AddDays(365).AddMinutes(-1)
            };

            if (Id > 0) CommonViewModel.Obj = _context.Using<ProductBatch>().GetByCondition(x => x.Id == Id).FirstOrDefault();

            CommonViewModel.Obj.MfgDate_Text = CommonViewModel.Obj.MfgDate?.ToString(Common.DateTimeFormat_ddMMyyyy).Replace("-", "/");
            CommonViewModel.Obj.ExpiryDate_Text = CommonViewModel.Obj.ExpiryDate?.ToString(Common.DateTimeFormat_ddMMyyyy).Replace("-", "/");
            CommonViewModel.Obj.CreatedDate_Text = CommonViewModel.Obj.CreatedDate?.ToString(Common.DateTimeFormat_ddMMyyyy_HHmm).Replace("-", "/");

            //List<SqlParameter> sqlParameters = new List<SqlParameter>();
            //sqlParameters.Add(new SqlParameter("@Id", SqlDbType.BigInt) { Value = 0 });

            var dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_Product_Combo", null, true);

            if (dt != null && dt.Rows.Count > 0)
                foreach (DataRow dr in dt.Rows)
                    CommonViewModel.SelectListItems.Add(new SelectListItem_Custom(dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "0", dr["Name"] != DBNull.Value ? Convert.ToString(dr["Name"]) : ""));

            if (CommonViewModel.Obj != null && CommonViewModel.Obj.ProductId > 0)
                CommonViewModel.Obj.Product_Text = CommonViewModel.SelectListItems.Where(x => x.Value == CommonViewModel.Obj.ProductId.ToString()).Select(x => x.Text).FirstOrDefault();
            if (CommonViewModel.Obj != null && CommonViewModel.Obj.PackageType_ID > 0)
                CommonViewModel.Obj.PackageType_Text = _context.Using<PackageType>().GetByCondition(x => x.Id == CommonViewModel.Obj.PackageType_ID).Select(x => x.PackageTypeName).FirstOrDefault();
            if (CommonViewModel.Obj != null && CommonViewModel.Obj.SKUSize_ID > 0)
                CommonViewModel.Obj.SKUSize_Text = _context.Using<SKUSize>().GetByCondition(x => x.Id == CommonViewModel.Obj.SKUSize_ID).Select(x => x.SKUSizeName).FirstOrDefault();
            CommonViewModel.Data5 = IsProductQRView;

            return PartialView("_Partial_AddEditForm", CommonViewModel);
        }

        [HttpPost]
        //[CustomAuthorizeAttribute(AccessType_Enum.Write)]
        public ActionResult Save(ProductBatch viewModel)
        {
            if (viewModel != null)
            {
                #region Validation

                if (!(Common.IsSuperAdmin() || Common.IsAdmin()))
                {
                    CommonViewModel.IsSuccess = false;
                    CommonViewModel.StatusCode = ResponseStatusCode.Error;
                    CommonViewModel.Message = ResponseStatusMessage.UnAuthorize;

                    return Json(CommonViewModel);
                }

                if (string.IsNullOrEmpty(viewModel.BatchNo))
                {
                    CommonViewModel.IsSuccess = false;
                    CommonViewModel.StatusCode = ResponseStatusCode.Error;
                    CommonViewModel.Message = "Please enter Batch No.";

                    return Json(CommonViewModel);
                }

                if (viewModel.ProductId <= 0)
                {
                    CommonViewModel.IsSuccess = false;
                    CommonViewModel.StatusCode = ResponseStatusCode.Error;
                    CommonViewModel.Message = "Please select Product.";

                    return Json(CommonViewModel);
                }
                if (viewModel.PackageType_ID <= 0)
                {
                    CommonViewModel.IsSuccess = false;
                    CommonViewModel.StatusCode = ResponseStatusCode.Error;
                    CommonViewModel.Message = "Please select Package type.";

                    return Json(CommonViewModel);
                }
                if (viewModel.SKUSize_ID <= 0)
                {
                    CommonViewModel.IsSuccess = false;
                    CommonViewModel.StatusCode = ResponseStatusCode.Error;
                    CommonViewModel.Message = "Please select SKU Size.";

                    return Json(CommonViewModel);
                }

                if (string.IsNullOrEmpty(viewModel.MfgDate_Text))
                {
                    CommonViewModel.IsSuccess = false;
                    CommonViewModel.StatusCode = ResponseStatusCode.Error;
                    CommonViewModel.Message = "Please enter Manufacture Date.";

                    return Json(CommonViewModel);
                }

                if (string.IsNullOrEmpty(viewModel.ExpiryDate_Text))
                {
                    CommonViewModel.IsSuccess = false;
                    CommonViewModel.StatusCode = ResponseStatusCode.Error;
                    CommonViewModel.Message = "Please enter Expiry Date.";

                    return Json(CommonViewModel);
                }

                if (!string.IsNullOrEmpty(viewModel.MfgDate_Text)) { try { viewModel.MfgDate = DateTime.ParseExact(viewModel.MfgDate_Text.Replace("-", "/"), Common.DateTimeFormat_ddMMyyyy, CultureInfo.InvariantCulture); } catch { } }

                if (!string.IsNullOrEmpty(viewModel.ExpiryDate_Text)) { try { viewModel.ExpiryDate = DateTime.ParseExact(viewModel.ExpiryDate_Text.Replace("-", "/"), Common.DateTimeFormat_ddMMyyyy, CultureInfo.InvariantCulture); } catch { } }

                #endregion

                #region Database-Transaction

                using (var transaction = _context.BeginTransaction())
                {
                    try
                    {
                        ProductBatch obj = _context.Using<ProductBatch>().GetByCondition(x => x.Id == viewModel.Id).FirstOrDefault();

                        if (obj != null)
                        {
                            obj.ProductId = viewModel.ProductId;
                            obj.MfgDate = viewModel.MfgDate;
                            obj.PackageType_ID = viewModel.PackageType_ID;
                            obj.SKUSize_ID = viewModel.SKUSize_ID;
                            obj.ExpiryDate = viewModel.ExpiryDate;
                           
                            obj.IsActive = true;
                            obj.IsDeleted = obj.IsActive ? false : obj.IsDeleted;

                            _context.Using<ProductBatch>().Update(obj);
                        }
                        else
                        {
                            long currentCount = _context.Using<ProductBatch>().GetByCondition(x => x.CreatedDate.Value.Year == DateTime.Now.Year).Count();

                            viewModel.BatchNo = DateTime.Now.ToString("yyyyMMdd") + (currentCount + 1).ToString().PadLeft(10, '0');

                            var _viewModel = _context.Using<ProductBatch>().Add(viewModel);
                            viewModel.Id = _viewModel.Id;
                        }

                        CommonViewModel.IsConfirm = true;
                        CommonViewModel.IsSuccess = true;
                        CommonViewModel.StatusCode = ResponseStatusCode.Success;

Views/ProductBatch/_Partial_AddEditForm.cshtml
@model ResponseModel<ProductBatch>

@{
	Layout = null;
}


<form id="formSave" action="@Url.Action("Save","ProductBatch")" method="post" class="w-100">
	<div class="card card-info">

		<div class="card-header">
			@if ((bool)Model.Data5)
			{
				<h3 class="card-title">Scan QR and Add Product in Batch</h3>
			}
			else
			{
				<h3 class="card-title">@(Model.Obj != null && Model.Obj.Id > 0 ? "Edit" : "Create") Product Batch</h3>
			}
			<input type="text" class="form-control d-none" id="Id" name="Id" value="@(Model.Obj != null && Model.Obj.Id > 0 ? Model.Obj.Id.ToString() : "")">
		</div>

		<div class="card-body">
			<div class="row no-gutters">
				<div class="col-12">
					<div class="form-group row">
						<label for="BatchNo" class="col-sm-2 col-form-label text-right">Batch No.</label>
						<div class="col-sm-4">
							<input type="text" class="form-control form-control-sm" id="BatchNo" name="BatchNo" value="@Model.Obj.BatchNo" autocomplete="off" readonly />
						</div>
					</div>

					<div class="form-group row">
						<label for="ProductId" class="col-sm-2 col-form-label text-right">Product </label>
						<div class="col-sm-4">
							@if (Model.Obj != null && Model.Obj.Id > 0 && Model.Obj.ProductId > 0)
							{
								<input type="text" class="form-control form-control-sm" value="@Model.Obj.Product_Text" readonly />
							}
							else
							{
								<select id="ProductId" name="ProductId" class="form-control form-control-sm select2 w-100" onchange="fnChangeProductDetail(this, 'PACKTYPE', '#PackageType_ID')">
									<option value="0">-- Select --</option>
									@if (Model.SelectListItems != null)
									{
										foreach (var item in Model.SelectListItems)
										{
											if (item.Value == Model.Obj.ProductId.ToString())
											{
												<option value="@item.Value" selected>@item.Text</option>
											}
											else
											{
												<option value="@item.Value">@item.Text</option>
											}
										}
									}
								</select>
							}
						</div>
						<label for="PackageType_ID" class="col-sm-2 col-form-label text-right">Package Type </label>
						<div class="col-sm-4">
							@if (Model.Obj != null && Model.Obj.Id > 0 && Model.Obj.PackageType_ID > 0)
							{
								<input type="text" class="form-control form-control-sm" value="@Model.Obj.PackageType_Text" readonly />
							}
							else
							{
								<select class="form-control form-control-sm select2 w-100" id="PackageType_ID" name="PackageType_ID" onchange="fnChangeProductDetail(this, 'SKUSIZE', '#SKUSize_ID')">
									<option value="0">-- Select --</option>
								</select>
							}
						</div>
						
					</div>

					<div class="form-group row">
						
						<label for="PackageType_ID" class="col-sm-2 col-form-label text-right">SKU Size </label>
						<div class="col-sm-4">
							@if (Model.Obj != null && Model.Obj.Id > 0 && Model.Obj.SKUSize_ID > 0)
							{
								<input type="text" class="form-control form-control-sm" value="@Model.Obj.SKUSize_Text" readonly />
							}
							else
							{
								<select class="form-control form-control-sm select2 w-100" id="SKUSize_ID" name="SKUSize_ID">
									<option value="0">-- Select --</option>
								</select>
							}
						</div>

						@if ((bool)Model.Data5)
						{
							<label for="QRCount" class="col-sm-2 col-form-label text-right">Generated QR Code Count</label>
							<div class="col-sm-4">
								<input type="text" class="form-control form-control-sm" id="QRCount" autocomplete="off" readonly />
							</div>
						}
					</div>

					<div class="form-group row">
						<label for="MfgDate_Text" class="col-sm-2 col-form-label text-right">Manufacture Date</label>
						<div class="col-sm-4">
							<input type="text" class="form-control form-control-sm datepicker" id="MfgDate_Text" name="MfgDate_Text" data-value="@Model.Obj.MfgDate_Text" autocomplete="off" @(Model.Obj != null && Model.Obj.MfgDate != null ? "readonly" : "") />
						</div>
						<label for="ExpiryDate_Text" class="col-sm-2 col-form-label text-right">Expiry Date</label>
						<div class="col-sm-4">
							<input type="text" class="form-control form-control-sm datepicker" id="ExpiryDate_Text" name="ExpiryDate_Text" data-value="@Model.Obj.ExpiryDate_Text" autocomplete="off" @(Model.Obj != null && Model.Obj.ExpiryDate != null ? "readonly" : "") />
						</div>
					</div>

				</div>
			</div>

			@if ((bool)Model.Data5)
			{
				<hr />
				<div class="row no-gutters">
					<div class="col-sm-12">
						<div class="form-group row">
							<label for="input_Scan_QR_Code" class="col-sm-2 col-form-label">Enter OR Code <span class="text-danger">*</span> <span class="float-right">:</span> </label>
							<div class="col-sm-6">
								<div class="input-group input-group-sm">
									<input type="text" id="input_Scan_QR_Code" class="form-control form-control-sm">
									<span class="input-group-append ml-2">
										<button type="button" class="btn btn-info btn-flat mr-2" onclick="$('#input_Scan_QR_Code').trigger('input');">Add</button>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row no-gooters">
					<div class="col-md-12 my-1">
						<table class="table table-bordered table-striped table-hover w-100" id="dataTable_ProductQRCode"></table>
					</div>
					<div class="clearfix"></div>
				</div>
			}
		</div>

		@if (!(bool)Model.Data5)
		{
			<div class="card-footer">
				<div class="row no-gutters">
					<div class="col-sm-1">&nbsp;</div>
					<div class="col-sm-6 text-left">
						<button type="submit" class="btn btn-success btnSubmit">Save</button>
						<button type="button" class="btn btn-danger" onclick="fnCloseParialView('divformSave', '.table_Common_SrNo');">Cancel</button>
					</div>
				</div>
			</div>
		}
	</div>

</form>