Models/Dealer.cs
namespace Seed_Admin
{
    public class Dealer : EntitiesBase
    {
        public override long  Id { get; set; }
        public string   User_ID { get; set; }
        public string   Password { get; set; }
        public string   BusinessName { get; set; }
		public string? Email { get; set; }
		public string? ContactNo { get; set; }
		public string AadharNumber { get; set; }
        public string GSTNumber { get; set; }       
        public decimal GeoLatitude { get; set; }
        public decimal GeoLongitude { get; set; }
        public long Country_Id { get; set; }
        public long State_Id { get; set; }
        public long District_Id { get; set; }
        public long City_Id { get; set; }
        public long Taluka_Id { get; set; }
        public string DistrictName { get; set; }
        public string VillageName { get; set; }
        public string TalukaName { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }
        public int PinCode { get; set; }
        public string AreaAllocated { get; set; }
        public string Address { get; set; }
    }
}

Controllers/DealerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Seed_Admin.Infra;
using System.Data;

namespace Seed_Admin.Controllers
{
	public class DealerController : BaseController<ResponseModel<Dealer>>
	{
		public DealerController(IRepositoryWrapper repository) : base(repository) { }

		public IActionResult Index()
		{
			try
			{
				var dt = new DataTable();

				CommonViewModel.ObjList = new List<Dealer>();

				List<SqlParameter> sqlParameters = new List<SqlParameter>();
				sqlParameters.Add(new SqlParameter("@Id", SqlDbType.BigInt) { Value = 0 });

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_DEALER_GET", sqlParameters, true);

				if (dt != null && dt.Rows.Count > 0)
				{
					foreach (DataRow dr in dt.Rows)
					{
						CommonViewModel.ObjList.Add(new Dealer()
						{
							Id = dr["Id"] != DBNull.Value ? Convert.ToInt64(dr["Id"]) : 0,
							User_ID = dr["User_ID"] != DBNull.Value ? Convert.ToString(dr["User_ID"]) : "",
							Password = dr["Password"] != DBNull.Value ? Convert.ToString(dr["Password"]) : "",
							BusinessName = dr["BusinessName"] != DBNull.Value ? Convert.ToString(dr["BusinessName"]) : "",
							Email = dr["Email"] != DBNull.Value ? Convert.ToString(dr["Email"]) : "",
							ContactNo = dr["ContactNo"] != DBNull.Value ? Convert.ToString(dr["ContactNo"]) : "",
							AadharNumber = dr["AadharNumber"] != DBNull.Value ? Convert.ToString(dr["AadharNumber"]) : "",
							GSTNumber = dr["GSTNumber"] != DBNull.Value ? Convert.ToString(dr["GSTNumber"]) : "",
							GeoLatitude = dr["GeoLatitude"] != DBNull.Value ? Convert.ToDecimal(dr["GeoLatitude"]) : 0,
							GeoLongitude = dr["GeoLongitude"] != DBNull.Value ? Convert.ToDecimal(dr["GeoLongitude"]) : 0,
							Country_Id = dr["Country_Id"] != DBNull.Value ? Convert.ToInt64(dr["Country_Id"]) : 0,
							State_Id = dr["State_Id"] != DBNull.Value ? Convert.ToInt64(dr["State_Id"]) : 0,
							District_Id = dr["District_Id"] != DBNull.Value ? Convert.ToInt64(dr["District_Id"]) : 0,
							Taluka_Id = dr["Taluka_Id"] != DBNull.Value ? Convert.ToInt64(dr["Taluka_Id"]) : 0,
							City_Id = dr["City_Id"] != DBNull.Value ? Convert.ToInt64(dr["City_Id"]) : 0,
							CountryName = dr["CountryName"] != DBNull.Value ? Convert.ToString(dr["CountryName"]) : "",
							StateName = dr["StateName"] != DBNull.Value ? Convert.ToString(dr["StateName"]) : "",
							DistrictName = dr["DistrictName"] != DBNull.Value ? Convert.ToString(dr["DistrictName"]) : "",
							TalukaName = dr["TalukaName"] != DBNull.Value ? Convert.ToString(dr["TalukaName"]) : "",
							VillageName = dr["VillageName"] != DBNull.Value ? Convert.ToString(dr["VillageName"]) : "",
							PinCode = dr["PinCode"] != DBNull.Value ? Convert.ToInt32(dr["PinCode"]) : 0,
							Address = dr["Address"] != DBNull.Value ? Convert.ToString(dr["Address"]) : "",
							AreaAllocated = dr["AreaAllocated"] != DBNull.Value ? Convert.ToString(dr["AreaAllocated"]) : ""


						});
					}
				}
			}
			catch (Exception ex) { LogService.LogInsert(GetCurrentAction(), "", ex); }

			return View(CommonViewModel);
		}

		[HttpGet]
		public IActionResult Partial_AddEditForm(long Id = 0)
		{
			var obj = new Dealer();

			var dt = new DataTable();

			var list = new List<SelectListItem_Custom>();

			try
			{

				List<SqlParameter> sqlParameters = new List<SqlParameter>();

				sqlParameters.Add(new SqlParameter("@Id", SqlDbType.BigInt) { Value = (Id > 0) ? Id : -1 });

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_DEALER_GET", sqlParameters, true);

				if (dt != null && dt.Rows.Count > 0 && Id > 0)
				{
					obj = new Dealer()
					{
						Id = dt.Rows[0]["Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["Id"]) : 0,
						User_ID = dt.Rows[0]["User_ID"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["User_ID"]) : "",
						Password = dt.Rows[0]["Password"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["Password"]) : "",
						BusinessName = dt.Rows[0]["BusinessName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["BusinessName"]) : "",
						Email = dt.Rows[0]["Email"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["Email"]) : "",
						ContactNo = dt.Rows[0]["ContactNo"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["ContactNo"]) : "",
						AadharNumber = dt.Rows[0]["AadharNumber"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["AadharNumber"]) : "",
						GSTNumber = dt.Rows[0]["GSTNumber"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["GSTNumber"]) : "",
						GeoLatitude = dt.Rows[0]["GeoLatitude"] != DBNull.Value ? Convert.ToDecimal(dt.Rows[0]["GeoLatitude"]) : 0,
						GeoLongitude = dt.Rows[0]["GeoLongitude"] != DBNull.Value ? Convert.ToDecimal(dt.Rows[0]["GeoLongitude"]) : 0,
						Country_Id = dt.Rows[0]["Country_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["Country_Id"]) : 0,
						State_Id = dt.Rows[0]["State_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["State_Id"]) : 0,
						District_Id = dt.Rows[0]["District_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["District_Id"]) : 0,
						Taluka_Id = dt.Rows[0]["Taluka_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["Taluka_Id"]) : 0,
						City_Id = dt.Rows[0]["City_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["City_Id"]) : 0,
						CountryName = dt.Rows[0]["CountryName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["CountryName"]) : "",
						StateName = dt.Rows[0]["StateName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["StateName"]) : "",
						DistrictName = dt.Rows[0]["DistrictName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["DistrictName"]) : "",
						TalukaName = dt.Rows[0]["TalukaName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["TalukaName"]) : "",
						VillageName = dt.Rows[0]["VillageName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["VillageName"]) : "",
						PinCode = dt.Rows[0]["PinCode"] != DBNull.Value ? Convert.ToInt32(dt.Rows[0]["PinCode"]) : 0,
						Address = dt.Rows[0]["Address"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["Address"]) : "",
						AreaAllocated = dt.Rows[0]["AreaAllocated"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["AreaAllocated"]) : ""
					};
				}
				else if (dt != null && dt.Rows.Count > 0)
					obj.User_ID = dt.Rows[0]["User_ID"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["User_ID"]) : "";

					sqlParameters = new List<SqlParameter>();
				sqlParameters.Add(new SqlParameter("@Country_Id", SqlDbType.BigInt) { Value = obj.Country_Id });
				dt = new DataTable();

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_State_Combo", sqlParameters, true);

				if (dt != null && dt.Rows.Count > 0)
				{
					foreach (DataRow dr in dt.Rows)
					{
						list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["StateName"]), "State")
						{
							Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
							Text = dr["StateName"] != DBNull.Value ? Convert.ToString(dr["StateName"]) : ""
						});
					}

				}
				sqlParameters = new List<SqlParameter>();
				sqlParameters.Add(new SqlParameter("@State_Id", SqlDbType.BigInt) { Value = obj.State_Id });
				dt = new DataTable();

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_District_Combo", sqlParameters, true);

				if (dt != null && dt.Rows.Count > 0)
				{
					foreach (DataRow dr in dt.Rows)
					{
						list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["Name"]), "District")
						{
							Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
							Text = dr["Name"] != DBNull.Value ? Convert.ToString(dr["Name"]) : ""
						});
					}

				}

				sqlParameters = new List<SqlParameter>();
				sqlParameters.Add(new SqlParameter("@District_Id", SqlDbType.BigInt) { Value = obj.District_Id });
				dt = new DataTable();

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_Taluka_Combo", sqlParameters, true);

				if (dt != null && dt.Rows.Count > 0)
				{
					foreach (DataRow dr in dt.Rows)
					{
						list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["Name"]), "Taluka")
						{
							Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
							Text = dr["Name"] != DBNull.Value ? Convert.ToString(dr["Name"]) : ""
						});
					}

				}
				sqlParameters = new List<SqlParameter>();
				sqlParameters.Add(new SqlParameter("@Taluka_Id", SqlDbType.BigInt) { Value = obj.Taluka_Id });
				dt = new DataTable();

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_City_Combo", sqlParameters, true);

				if (dt != null && dt.Rows.Count > 0)
				{
					foreach (DataRow dr in dt.Rows)
					{
						list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["Name"]), "Village")
						{
							Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
							Text = dr["Name"] != DBNull.Value ? Convert.ToString(dr["Name"]) : ""
						});
					}

				}


				dt = new DataTable();

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_Country_Combo", null, true);

				if (dt != null && dt.Rows.Count > 0)
				{
					foreach (DataRow dr in dt.Rows)
					{
						list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["CountryName"]), "Country")
						{
							Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
							Text = dr["CountryName"] != DBNull.Value ? Convert.ToString(dr["CountryName"]) : ""
						});
					}

				}
				obj.Password = obj.Password != null ? Common.Decrypt(obj.Password) : obj.Password;
				//    sqlParameters = new List<SqlParameter>();
				//    sqlParameters.Add(new SqlParameter("@Lov_Column", SqlDbType.NVarChar) { Value = "QUERY_TYPE" });

				//    dt = DataContext.ExecuteStoredProcedure_DataTable_SQL("SP_Lov_GET", oParams, true);

				//    if (dt != null && dt.Rows.Count > 0)
				//    {
				//        foreach (DataRow dr in dt.Rows)
				//        {

Views/Dealer/Index.cshtml
@model ResponseModel<Dealer>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var IndexPageUrl = "/" + ViewContext.RouteData.Values["Controller"].ToString() + "/Index";
}

@section Styles {
	<style>
		.eye-pass {
			position: absolute;
			margin-top: 15px;
			top: -4px;
			right: 0;
			margin-right: 35px;
			cursor: pointer;
		}

		input[type=password]::-ms-reveal,
		input[type=password]::-ms-clear {
			display: none;
		}
	</style>
}

<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Dealer</h1>
			</div>
			<div class="col-sm-6">
				<div class="float-sm-right">
					@*@if (Model.IsCreate == true)
					{*@
					<button type="button" id="btnAddNewItem" class="btn btn-primary btn-md pull-right mr-2 divformSave_Hide" onclick="fnLoadParialView('divformSave', '@Url.Action("Partial_AddEditForm", "Dealer")');">
						<i class="fas fa-plus"></i> &nbsp; Add Dealer
					</button>
					@*}*@
				</div>
			</div>
		</div>
	</div>
</div>
<section class="content">
	<div class="container-fluid">
		<div class="row no-gutters divformSave_Display d-none" style="margin: 5px !important;">
			<div class="col-12">
				<form id="formSave" asp-controller="Dealer" asp-action="Save" method="post" class="form-horizontal" enctype="multipart/form-data">
					<div class="row no-gutters" id="divformSave"></div>
					<div class="clearfix"></div>
					<hr />
				</form>
			</div>
		</div>
		<div class="row clearfix pt-2">
			<div class="col-12">
				<div class="card card-primary card-outline">

					<div class="card-body">
						<div class="row no-gooters">
							<div class="col-md-12 my-1">
								<table class="table table-bordered table-striped table_Common_SrNo">
									<thead>
										<tr>
											<th width="5%">#</th>
											@* <th>User ID</th> *@
											<th>Business Name</th>
											<th>Email </th>
											<th>Contact No. </th>
											<th>Aadhar No</th>											
											<th>GST No</th>	
											<th>Country</th>
											<th>State</th>
											<th>District</th>
											<th>Taluka</th>
											<th>Village</th>
											<th width="5%">Action</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model.ObjList)
										{
											<tr>
												<td></td>
												@* <td>@item.User_ID</td> *@
												<td>@item.BusinessName</td>
												<td>@item.Email</td>
												<td>@item.ContactNo</td>
												<td>@item.AadharNumber</td>
												<td>@item.GSTNumber</td>												
												<td>@item.CountryName</td>												
												<td>@item.StateName</td>												
												<td>@item.DistrictName</td>												
												<td>@item.TalukaName</td>												
												<td>@item.VillageName</td>												
												<td>
													<div class="btn-group">
														<button type="button" class="btn btn-info btn-sm btn-flat" data-toggle="tooltip" data-placement="top" title="Edit"
																onclick="fnLoadParialView('divformSave', '@Url.Action("Partial_AddEditForm", "Dealer")?Id=@item.Id');">
															<i class="far fa-edit"></i>
														</button>

														<button type="button" class="btn btn-danger btn-sm btn-flat ml-2" data-toggle="tooltip" data-placement="top" title="Delete"
																onclick="fnDelete_Confirm('@Url.Action("DeleteConfirmed", "Dealer")?Id=@item.Id');">
															<i class="far fa-trash-alt"></i>
														</button>

													</div>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>

							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

@section Scripts {
	<script type="text/javascript">
		$(document).ready(function () {
			//$('[data-toggle="tooltip"]').tooltip();
			$('[data-toggle="tooltip"]').tooltip();

			$('.btn').on('click', function () {
				$(this).tooltip('hide'); // Hide the tooltip
			});
		});

		function fnChange_CountryStateCityDistrictVillageTaluka($this, $type, $selector) {

			if (typeof $selector != 'undefined' && $selector != null && $selector.length > 0) {
				ShowLoader(true);

				 if (typeof $type != 'undefined' && $type != null && $type.length > 0 && $type == 'STATE') {
					$('#District_Id').empty().append('<option value="0">-- Select --</option>');
					$('#Taluka_Id').empty().append('<option value="0">-- Select --</option>');
					$('#Village_Id').empty().append('<option value="0">-- Select --</option>');
				 }
				 else if (typeof $type != 'undefined' && $type != null && $type.length > 0 && $type == 'DISTRICT') {
					$('#Taluka_Id').empty().append('<option value="0">-- Select --</option>');
					$('#Village_Id').empty().append('<option value="0">-- Select --</option>');

				 }
				 else if (typeof $type != 'undefined' && $type != null && $type.length > 0 && $type == 'TALUKA') {
					$('#Village_Id').empty().append('<option value="0">-- Select --</option>');
				 }




				var stateDropdown = $($selector);
				stateDropdown.empty();
				stateDropdown.append('<option value="0">-- Select --</option>');

				var $url = '@Url.Action("GetCountryStateDistrictVillageTaluka", "Dealer")?Type=' + $type + '&ParentId=' + $($this).val();

				$.ajax({
					url: $url,
					type: 'GET',
					data: {},
					dataType: "json",
					success: function (response) {
						debugger;
						ShowLoader(false);
						$.each(response, function (index, state) {
							stateDropdown.append('<option value="' + state.Value + '">' + state.Text + '</option>');
						});

					},
					failure: function () { ShowLoader(false); CommonAlert_Error(null); },
					error: function () { ShowLoader(false); CommonAlert_Error(null); }
				});
			}

		}
		

	</script>
}