Models/Plant.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Seed_Admin.Models
{
	public class Plant : EntitiesBase
	{
		public override long Id { get; set; }

		public string PlantCode { get; set; } = null!;

		public string PlantName { get; set; } = null!;

		public string? AddressLine1 { get; set; }

		public string? AddressLine2 { get; set; }

		public long Country_Id { get; set; }

		public long State_Id { get; set; }

		public long District_Id { get; set; }

		public long Taluka_Id { get; set; }

		public long City_Id { get; set; }

		public int? PinCode { get; set; }

		[NotMapped] public string DistrictName { get; set; }
		[NotMapped] public string VillageName { get; set; }
		[NotMapped] public string TalukaName { get; set; }
		[NotMapped] public string CountryName { get; set; }
		[NotMapped] public string StateName { get; set; }


	}
}

Controllers/PlantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Seed_Admin.Infra;
using Seed_Admin.Models;
using System.Data;

namespace Seed_Admin.Controllers
{
	public class PlantController : BaseController<ResponseModel<Plant>>
	{
		public PlantController(IRepositoryWrapper repository) : base(repository) { }

		public IActionResult Index()
		{
			try
			{
				var dt = new DataTable();

				CommonViewModel.ObjList = new List<Plant>();

				List<SqlParameter> sqlParameters = new List<SqlParameter>();
				sqlParameters.Add(new SqlParameter("@Id", SqlDbType.BigInt) { Value = 0 });

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_Plant_GET", sqlParameters, true);

				if (dt != null && dt.Rows.Count > 0)
				{
					foreach (DataRow dr in dt.Rows)
					{
						CommonViewModel.ObjList.Add(new Plant()
						{
							Id = dr["Id"] != DBNull.Value ? Convert.ToInt64(dr["Id"]) : 0,
							PlantCode = dr["PlantCode"] != DBNull.Value ? Convert.ToString(dr["PlantCode"]) : "",
							PlantName = dr["PlantName"] != DBNull.Value ? Convert.ToString(dr["PlantName"]) : "",
							AddressLine1 = dr["AddressLine1"] != DBNull.Value ? Convert.ToString(dr["AddressLine1"]) : "",
							AddressLine2 = dr["AddressLine2"] != DBNull.Value ? Convert.ToString(dr["AddressLine2"]) : "",
							Country_Id = dr["Country_Id"] != DBNull.Value ? Convert.ToInt64(dr["Country_Id"]) : 0,
							State_Id = dr["State_Id"] != DBNull.Value ? Convert.ToInt64(dr["State_Id"]) : 0,
							District_Id = dr["District_Id"] != DBNull.Value ? Convert.ToInt64(dr["District_Id"]) : 0,
							Taluka_Id = dr["Taluka_Id"] != DBNull.Value ? Convert.ToInt64(dr["Taluka_Id"]) : 0,
							City_Id = dr["City_Id"] != DBNull.Value ? Convert.ToInt64(dr["City_Id"]) : 0,
							CountryName = dr["CountryName"] != DBNull.Value ? Convert.ToString(dr["CountryName"]) : "",
							StateName = dr["StateName"] != DBNull.Value ? Convert.ToString(dr["StateName"]) : "",
							DistrictName = dr["DistrictName"] != DBNull.Value ? Convert.ToString(dr["DistrictName"]) : "",
							TalukaName = dr["TalukaName"] != DBNull.Value ? Convert.ToString(dr["TalukaName"]) : "",
							VillageName = dr["VillageName"] != DBNull.Value ? Convert.ToString(dr["VillageName"]) : "",
							PinCode = dr["Pincode"] != DBNull.Value ? Convert.ToInt32(dr["Pincode"]) : 0


						});
					}
				}
			}
			catch (Exception ex) { LogService.LogInsert(GetCurrentAction(), "", ex); }

			return View(CommonViewModel);
		}

		[HttpGet]
		public IActionResult Partial_AddEditForm(long Id = 0)
		{
			var obj = new Plant();

			var dt = new DataTable();

			var list = new List<SelectListItem_Custom>();

			try
			{

				List<SqlParameter> sqlParameters = new List<SqlParameter>();
				if (Id > 0)
				{
					sqlParameters.Add(new SqlParameter("@Id", SqlDbType.BigInt) { Value = Id });

					dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_Plant_GET", sqlParameters, true);

					if (dt != null && dt.Rows.Count > 0)
					{
						obj = new Plant()
						{
							Id = dt.Rows[0]["Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["Id"]) : 0,
							PlantCode = dt.Rows[0]["PlantCode"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["PlantCode"]) : "",
							PlantName = dt.Rows[0]["PlantName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["PlantName"]) : "",
							AddressLine1 = dt.Rows[0]["AddressLine1"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["AddressLine1"]) : "",
							AddressLine2 = dt.Rows[0]["AddressLine2"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["AddressLine2"]) : "",
							Country_Id = dt.Rows[0]["Country_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["Country_Id"]) : 0,
							State_Id = dt.Rows[0]["State_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["State_Id"]) : 0,
							District_Id = dt.Rows[0]["District_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["District_Id"]) : 0,
							Taluka_Id = dt.Rows[0]["Taluka_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["Taluka_Id"]) : 0,
							City_Id = dt.Rows[0]["City_Id"] != DBNull.Value ? Convert.ToInt64(dt.Rows[0]["City_Id"]) : 0,
							CountryName = dt.Rows[0]["CountryName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["CountryName"]) : "",
							StateName = dt.Rows[0]["StateName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["StateName"]) : "",
							DistrictName = dt.Rows[0]["DistrictName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["DistrictName"]) : "",
							TalukaName = dt.Rows[0]["TalukaName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["TalukaName"]) : "",
							VillageName = dt.Rows[0]["VillageName"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["VillageName"]) : "",
							PinCode = dt.Rows[0]["PinCode"] != DBNull.Value ? Convert.ToInt32(dt.Rows[0]["PinCode"]) : 0,
						
						};
					}


					sqlParameters = new List<SqlParameter>();
					sqlParameters.Add(new SqlParameter("@Country_Id", SqlDbType.BigInt) { Value = obj.Country_Id });
					dt = new DataTable();

					dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_State_Combo", sqlParameters, true);

					if (dt != null && dt.Rows.Count > 0)
					{
						foreach (DataRow dr in dt.Rows)
						{
							list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["StateName"]), "State")
							{
								Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
								Text = dr["StateName"] != DBNull.Value ? Convert.ToString(dr["StateName"]) : ""
							});
						}

					}
					sqlParameters = new List<SqlParameter>();
					sqlParameters.Add(new SqlParameter("@State_Id", SqlDbType.BigInt) { Value = obj.State_Id });
					dt = new DataTable();

					dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_District_Combo", sqlParameters, true);

					if (dt != null && dt.Rows.Count > 0)
					{
						foreach (DataRow dr in dt.Rows)
						{
							list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["Name"]), "District")
							{
								Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
								Text = dr["Name"] != DBNull.Value ? Convert.ToString(dr["Name"]) : ""
							});
						}

					}

					sqlParameters = new List<SqlParameter>();
					sqlParameters.Add(new SqlParameter("@District_Id", SqlDbType.BigInt) { Value = obj.District_Id });
					dt = new DataTable();

					dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_Taluka_Combo", sqlParameters, true);

					if (dt != null && dt.Rows.Count > 0)
					{
						foreach (DataRow dr in dt.Rows)
						{
							list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["Name"]), "Taluka")
							{
								Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
								Text = dr["Name"] != DBNull.Value ? Convert.ToString(dr["Name"]) : ""
							});
						}

					}
					sqlParameters = new List<SqlParameter>();
					sqlParameters.Add(new SqlParameter("@Taluka_Id", SqlDbType.BigInt) { Value = obj.Taluka_Id });
					dt = new DataTable();

					dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_City_Combo", sqlParameters, true);

					if (dt != null && dt.Rows.Count > 0)
					{
						foreach (DataRow dr in dt.Rows)
						{
							list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["Name"]), "Village")
							{
								Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
								Text = dr["Name"] != DBNull.Value ? Convert.ToString(dr["Name"]) : ""
							});
						}

					}

				}


				dt = new DataTable();

				dt = DataContext_Command.ExecuteStoredProcedure_DataTable("SP_Country_Combo", null, true);

				if (dt != null && dt.Rows.Count > 0)
				{
					foreach (DataRow dr in dt.Rows)
					{
						list.Add(new SelectListItem_Custom(Convert.ToString(dr["Id"]), Convert.ToString(dr["CountryName"]), "Country")
						{
							Value = dr["Id"] != DBNull.Value ? Convert.ToString(dr["Id"]) : "",
							Text = dr["CountryName"] != DBNull.Value ? Convert.ToString(dr["CountryName"]) : ""
						});
					}

				}
				
				//    sqlParameters = new List<SqlParameter>();
				//    sqlParameters.Add(new SqlParameter("@Lov_Column", SqlDbType.NVarChar) { Value = "QUERY_TYPE" });

				//    dt = DataContext.ExecuteStoredProcedure_DataTable_SQL("SP_Lov_GET", oParams, true);

				//    if (dt != null && dt.Rows.Count > 0)
				//    {
				//        foreach (DataRow dr in dt.Rows)
				//        {
				//            list.Add(new SelectListItem_Custom(Convert.ToString(dr["LOV_CODE"]), Convert.ToString(dr["LOV_DESC"]), "QUERY_TYPE")
				//            {
				//                Value = dr["LOV_CODE"] != DBNull.Value ? Convert.ToString(dr["LOV_CODE"]) : "",
				//                Text = dr["LOV_DESC"] != DBNull.Value ? Convert.ToString(dr["LOV_DESC"]) : ""
				//            });
				//        }
				//    }

			}
			catch (Exception ex) { LogService.LogInsert(GetCurrentAction(), "", ex); }

			CommonViewModel.SelectListItems = list;
			CommonViewModel.Obj = obj;

			return PartialView("_Partial_AddEditForm", CommonViewModel);
		}
		[HttpPost]
		public JsonResult Save(Plant viewModel)
		{
			try
			{

				if (string.IsNullOrEmpty(viewModel.PlantCode))
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;
					CommonViewModel.Message = "Please enter Plant Code.";

					return Json(CommonViewModel);
				}

				if (string.IsNullOrEmpty(viewModel.PlantName))
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;
					CommonViewModel.Message = "Please enter PlantName.";

					return Json(CommonViewModel);
				}
				if (string.IsNullOrEmpty(viewModel.AddressLine1))
				{
					CommonViewModel.IsSuccess = false;
					CommonViewModel.StatusCode = ResponseStatusCode.Error;
					CommonViewModel.Message = "Please enter AddressLine1 name.";

					return Json(CommonViewModel);
				}
				var (IsSuccess, response, Id) = (false, ResponseStatusMessage.Error, 0M);

Views/Plant/Index.cshtml
@model ResponseModel<Plant>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var IndexPageUrl = "/" + ViewContext.RouteData.Values["Controller"].ToString() + "/Index";
}

<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Plant</h1>
			</div>
			<div class="col-sm-6">
				<div class="float-sm-right">
					@*@if (Model.IsCreate == true)
					{*@
					<button type="button" id="btnAddNewItem" class="btn btn-primary btn-md pull-right mr-2 divformSave_Hide" onclick="fnLoadParialView('divformSave', '@Url.Action("Partial_AddEditForm", "Plant")');">
						<i class="fas fa-plus"></i> &nbsp; Add Plant
					</button>
					@*}*@
				</div>
			</div>
		</div>
	</div>
</div>
<section class="content">
	<div class="container-fluid">
		<div class="row no-gutters divformSave_Display d-none" style="margin: 5px !important;">
			<div class="col-12">
				<form id="formSave" asp-controller="Plant" asp-action="Save" method="post" class="form-horizontal" enctype="multipart/form-data">
					<div class="row no-gutters" id="divformSave"></div>
					<div class="clearfix"></div>
					<hr />
				</form>
			</div>
		</div>
		<div class="row clearfix pt-2">
			<div class="col-12">
				<div class="card card-primary card-outline">

					<div class="card-body">
						<div class="row no-gooters">
							<div class="col-md-12 my-1">
								<table class="table table-bordered table-striped table_Common_SrNo">
									<thead>
										<tr>
											<th width="5%">#</th>
											<th>PlantCode</th> 
											<th>PlantName</th>
								
											<th width="5%">Action</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model.ObjList)
										{
											<tr>
												<td></td>
												<td>@item.PlantCode</td> 
												<td>@item.PlantName</td>
											
												<td>
													<div class="btn-group">
														<button type="button" class="btn btn-info btn-sm btn-flat" data-toggle="tooltip" data-placement="top" title="Edit"
																onclick="fnLoadParialView('divformSave', '@Url.Action("Partial_AddEditForm", "Plant")?Id=@item.Id');">
															<i class="far fa-edit"></i>
														</button>

														<button type="button" class="btn btn-danger btn-sm btn-flat ml-2" data-toggle="tooltip" data-placement="top" title="Delete"
																onclick="fnDelete_Confirm('@Url.Action("DeleteConfirmed", "Plant")?Id=@item.Id');">
															<i class="far fa-trash-alt"></i>
														</button>

													</div>
												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>

							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

@section Scripts {
	<script type="text/javascript">
		$(document).ready(function () {
			//$('[data-toggle="tooltip"]').tooltip();
			$('[data-toggle="tooltip"]').tooltip();

			$('.btn').on('click', function () {
				$(this).tooltip('hide'); // Hide the tooltip
			});
		});

		function fnChange_CountryStateCityDistrictVillageTaluka($this, $type, $selector) {

			if (typeof $selector != 'undefined' && $selector != null && $selector.length > 0) {
				ShowLoader(true);

				 if (typeof $type != 'undefined' && $type != null && $type.length > 0 && $type == 'STATE') {
					$('#District_Id').empty().append('<option value="0">-- Select --</option>');
					$('#Taluka_Id').empty().append('<option value="0">-- Select --</option>');
					$('#Village_Id').empty().append('<option value="0">-- Select --</option>');
				 }
				 else if (typeof $type != 'undefined' && $type != null && $type.length > 0 && $type == 'DISTRICT') {
					$('#Taluka_Id').empty().append('<option value="0">-- Select --</option>');
					$('#Village_Id').empty().append('<option value="0">-- Select --</option>');

				 }
				 else if (typeof $type != 'undefined' && $type != null && $type.length > 0 && $type == 'TALUKA') {
					$('#Village_Id').empty().append('<option value="0">-- Select --</option>');
				 }




				var stateDropdown = $($selector);
				stateDropdown.empty();
				stateDropdown.append('<option value="0">-- Select --</option>');

				var $url = '@Url.Action("GetCountryStateDistrictVillageTaluka", "Dealer")?Type=' + $type + '&ParentId=' + $($this).val();

				$.ajax({
					url: $url,
					type: 'GET',
					data: {},
					dataType: "json",
					success: function (response) {
						debugger;
						ShowLoader(false);
						$.each(response, function (index, state) {
							stateDropdown.append('<option value="' + state.Value + '">' + state.Text + '</option>');
						});

					},
					failure: function () { ShowLoader(false); CommonAlert_Error(null); },
					error: function () { ShowLoader(false); CommonAlert_Error(null); }
				});
			}

		}


	</script>
}

Views/Plant/_Partial_AddEditForm.cshtml
@model ResponseModel<Plant>

@{
	Layout = null;
}

<div class="col-md-12">
	<div class="card card-primary card-outline">

		<div class="card-header">
			<h3 class="card-title">@(Model.Obj != null && Model.Obj.Id > 0 ? "Edit" : "Create") Plant</h3>
			<input type="text" class="form-control d-none" id="Id" name="Id" value="@(Model.Obj != null && Model.Obj.Id > 0 ? Model.Obj.Id.ToString() : "")">

		</div>

		<div class="card-body">
			<div class="row no-gutters">
				<div class="col-12">
					<div class="form-group row">
						<label for="Obj.PlantCode" class="col-sm-2 col-form-label text-right">Plant Code<span style="color:red">*</span></label>
						<div class="col-sm-4">
							<input type="text" class="form-control form-control-sm" id="PlantCode" name="PlantCode" value="@Model.Obj.PlantCode" placeholder="Plant Code" autocomplete="off">
						</div>
						<label for="Obj.PlantName" class="col-sm-2 col-form-label text-right">Plant Name</label>
						<div class="col-sm-4">
							<div class="input-group mb-3">
								<input type="text" data-altType="text" class="form-control form-control-sm" id="PlantName" name="PlantName" placeholder="Plant Name" autocomplete="off" value="@Model.Obj.PlantName">
							
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label for="Obj.DealerName" class="col-sm-2 col-form-label text-right">AddressLine1<span style="color:red">*</span></label>
						<div class="col-sm-4">
							<input type="text" class="form-control form-control-sm" id="AddressLine1" name="AddressLine1" value="@Model.Obj.AddressLine1" placeholder="AddressLine1" autocomplete="off">
						</div>
						<label for="Obj.Password" class="col-sm-2 col-form-label text-right">AddressLine2</label>
						<div class="col-sm-4">
							<div class="input-group mb-3">
								<input type="text" class="form-control form-control-sm" id="AddressLine2" name="AadharNumber" value="@Model.Obj.AddressLine2" placeholder="AddressLine2" autocomplete="off">
							</div>
						</div>
					</div>
					
					<div class="form-group row">
						<label class="form-control-label col-sm-2" style="line-height: 2.5;">Country</label>
						<div class="col-sm-4">
							<select class="form-control show-tick select2" id="Country_Id" name="Country_Id" onchange="fnChange_CountryStateCityDistrictVillageTaluka(this, 'STATE', '#State_Id')">
								<option value="0">-- Select --</option>
								@if (Model.SelectListItems != null && Model.SelectListItems.Count > 0)
								{
									foreach (SelectListItem_Custom item in Model.SelectListItems.Where(x => x.Group == "Country"))
									{
										if (item.Value.ToUpper() == Model.Obj.Country_Id.ToString())
										{
											<option value="@item.Value" selected>@item.Text</option>
										}
										else
										{
											<option value="@item.Value">@item.Text</option>
										}
									}
								}
							</select>
						</div>
					   <label class="form-control-label col-sm-2" style="line-height: 2.5;">State</label>
						<div class="col-sm-4">
							<select class="form-control show-tick select2" id="State_Id" name="State_Id" onchange="fnChange_CountryStateCityDistrictVillageTaluka(this, 'DISTRICT', '#District_Id')">
								<option value="0">-- Select --</option>
								@if (Model.SelectListItems != null && Model.SelectListItems.Count > 0)
								{
									foreach (SelectListItem_Custom item in Model.SelectListItems.Where(x => x.Group == "State"))
									{
										if (item.Value.ToUpper() == Model.Obj.State_Id.ToString())
										{
											<option value="@item.Value" selected>@item.Text</option>
										}
										else
										{
											<option value="@item.Value">@item.Text</option>
										}
									}
								}
							</select>
						</div>
					</div>
					<div class="form-group row">
						<label class="form-control-label col-sm-2" style="line-height: 2.5;">District</label>
						<div class="col-sm-4">
							<select class="form-control show-tick select2" id="District_Id" name="District_Id" onchange="fnChange_CountryStateCityDistrictVillageTaluka(this, 'TALUKA', '#Taluka_Id')">
								<option value="0">-- Select --</option>
								@if (Model.SelectListItems != null && Model.SelectListItems.Count > 0)
								{
									foreach (SelectListItem_Custom item in Model.SelectListItems.Where(x => x.Group == "District"))
									{
										if (item.Value.ToUpper() == Model.Obj.District_Id.ToString())
										{
											<option value="@item.Value" selected>@item.Text</option>
										}
										else
										{
											<option value="@item.Value">@item.Text</option>
										}
									}
								}
							</select>

						</div>
						<label class="form-control-label col-sm-2" style="line-height: 2.5;">Taluka</label>
						<div class="col-sm-4">
							<select class="form-control show-tick select2" id="Taluka_Id" name="Taluka_Id" onchange="fnChange_CountryStateCityDistrictVillageTaluka(this, 'VILLAGE', '#City_Id')">
								<option value="0">-- Select --</option>
								@if (Model.SelectListItems != null && Model.SelectListItems.Count > 0)
								{
									foreach (SelectListItem_Custom item in Model.SelectListItems.Where(x => x.Group == "Taluka"))
									{
										if (item.Value.ToUpper() == Model.Obj.Taluka_Id.ToString())
										{
											<option value="@item.Value" selected>@item.Text</option>
										}
										else
										{
											<option value="@item.Value">@item.Text</option>
										}
									}
								}
							</select>
						</div>
					</div>
					<div class="form-group row">
						<label class="form-control-label col-sm-2" style="line-height: 2.5;">City</label>
						<div class="col-sm-4">
							<select class="form-control show-tick select2" id="City_Id" name="City_Id">
								<option value="0">-- Select --</option>
								@if (Model.SelectListItems != null && Model.SelectListItems.Count > 0)
								{
									foreach (SelectListItem_Custom item in Model.SelectListItems.Where(x => x.Group == "Village"))
									{
										if (item.Value.ToUpper() == Model.Obj.City_Id.ToString())
										{
											<option value="@item.Value" selected>@item.Text</option>
										}
										else
										{
											<option value="@item.Value">@item.Text</option>
										}
									}
								}
							</select>

						</div>
						<label for="Obj.Password" class="col-sm-2 col-form-label text-right">PinCode</label>
						<div class="col-sm-4">
							<input type="text" class="form-control form-control-sm isNumberKey" id="PinCode" name="PinCode" value="@Model.Obj.PinCode" placeholder="PinCode" autocomplete="off" maxlength="6">
						</div>
					</div>

				</div>

			</div>

		</div>

		<div class="card-footer">
			<div class="row no-gutters">
				<div class="col-sm-1">&nbsp;</div>
				<div class="col-sm-12 text-center">
					<button type="submit" class="btn btn-success btnSubmit">Save</button>
					<button type="button" class="btn btn-danger" onclick="fnCloseParialView('divformSave','#table_Common_SrNo')">Cancel</button>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<script type="text/javascript">
		$(document).ready(function () {

		});
	</script>
}